version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  etl:
    build: ./etl
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: questions_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql-data:

